AllCops:
  TargetRubyVersion: 2.4.1

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 120

# Disable class documentation.
Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

# Exclude BlockLength Cop for specs.
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - /**/**/*_spec.rb
