language: ruby
rvm:
- 2.2.3

before_script:
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible -y && sudo apt-get update && sudo apt-get install -y ansible
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
bundler_args: "--without play"
notifications:
  email:
    recipients:
      - antnruban@gmail.com
      - sanya.davyskiba@gmail.com
    on_success: never
    on_failure: always
after_success:
  - git clone https://github.com/tickmo/ansible_deploy.git $HOME/ansible_deploy
  - cd $HOME/ansible_deploy && ansible-playbook plays/deploy.yml
