language: ruby
rvm:
- 2.2.3

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
bundler_args: "--without play"
notifications:
  email:
    recipients:
      - antnruban@gmail.com
      - sanya.davyskiba@gmail.com
    on_success: never
    on_failure: always
